"on":
  push:
    branches:
    - main
name: Deploy to test-4009d71b
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: "9"
        PORTER_HOST: https://newt-worthy-gazelle.ngrok-free.app
        PORTER_PROJECT: "1"
        PORTER_STACK_NAME: test-4009d71b
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1_9 }}
